// ===========================================================
// AI IMPROVEMENT - Claude API Integration
// ===========================================================

// GENERATE IMPROVEMENT PLAN
window.generateImprovementPlan = async function() {
  if (!window.CAN_AI.includes(window.currentUser?.role)) {
    alert('You need Manager role or above to use AI features.');
    return;
  }

  const procId = document.getElementById('ai-proc-id')?.value;
  
  if (!procId) {
    alert('Please select a process first.');
    return;
  }

  const proc = window.processes.find(p => p.id === procId);
  if (!proc) {
    alert('Process not found.');
    return;
  }

  // Get related data
  const procSteps = window.steps.filter(s => s.process_id === procId);
  const procGaps = window.gaps.filter(g => g.process_id === procId);
  const procMetrics = window.metrics.filter(m => m.process_id === procId);

  // Show loading
  const outputDiv = document.getElementById('ai-output');
  if (outputDiv) {
    outputDiv.innerHTML = '<div class="ai-thinking"><div class="spinner"></div>Analyzing process and generating improvement plan...</div>';
    outputDiv.style.display = 'block';
  }

  // Get API key and model from localStorage
  const apiKey = localStorage.getItem('ai_api_key');
  const model = localStorage.getItem('ai_model') || 'claude-3-5-sonnet-20241022';
  const maxTokens = parseInt(localStorage.getItem('ai_max_tokens') || '2000');

  if (!apiKey) {
    if (outputDiv) {
      outputDiv.innerHTML = '<div style="padding:1rem;background:#fee;border:1px solid #fcc;border-radius:8px;color:#c00;">⚠️ No API key configured. Go to CONFIG → Integration to add your API key.</div>';
    }
    return;
  }

  // Determine provider from model name
  let apiUrl, headers, requestBody;
  
  if (model.startsWith('claude')) {
    // Anthropic Claude
    apiUrl = 'https://api.anthropic.com/v1/messages';
    headers = {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01'
    };
    requestBody = {
      model: model,
      max_tokens: maxTokens,
      messages: [{
        role: 'user',
        content: `You are a process improvement expert. Analyze this business process and provide a detailed improvement plan with specific, actionable recommendations.

${context}

Provide:
1. Executive Summary (2-3 sentences)
2. Key Issues Identified (prioritized list)
3. Improvement Recommendations (specific actions with expected impact)
4. Quick Wins (can implement within 1 week)
5. Medium-term Actions (1-3 months)
6. Success Metrics (how to measure improvement)

Be specific, practical, and focus on the most impactful changes.`
      }]
    };
  } else if (model.startsWith('gpt')) {
    // OpenAI
    apiUrl = 'https://api.openai.com/v1/chat/completions';
    headers = {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    };
    requestBody = {
      model: model,
      max_tokens: maxTokens,
      messages: [{
        role: 'user',
        content: `You are a process improvement expert. Analyze this business process and provide a detailed improvement plan.

${context}

Provide: Executive Summary, Key Issues, Recommendations, Quick Wins, Medium-term Actions, Success Metrics.`
      }]
    };
  } else {
    if (outputDiv) {
      outputDiv.innerHTML = '<div style="padding:1rem;background:#fee;border:1px solid #fcc;border-radius:8px;color:#c00;">⚠️ Unsupported model selected. Please choose Claude or GPT model.</div>';
    }
    return;
  }

  try {
    // Call AI API
    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: headers,
      body: JSON.stringify(requestBody)
    });

    const data = await response.json();

    if (data.error) {
      throw new Error(data.error.message || 'API request failed');
    }

    // Extract text based on provider
    let aiText;
    if (model.startsWith('claude')) {
      aiText = data.content[0].text;
    } else if (model.startsWith('gpt')) {
      aiText = data.choices[0].message.content;
    }

    // Display result
    if (outputDiv) {
      outputDiv.innerHTML = `
        <div class="ai-output">
          <h3>🚀 AI-Generated Improvement Plan</h3>
          <div style="white-space:pre-wrap;line-height:1.8;">${escapeHtml(aiText)}</div>
          <div style="margin-top:1.5rem;padding-top:1rem;border-top:1px solid rgba(124,58,237,.2);font-size:.75rem;color:#999;">
            Generated by ${model} • ${new Date().toLocaleString()}
          </div>
        </div>
      `;
    }

  } catch (error) {
    console.error('AI generation error:', error);
    if (outputDiv) {
      outputDiv.innerHTML = `<div style="padding:1rem;background:#fee;border:1px solid #fcc;border-radius:8px;color:#c00;">⚠️ Error: ${error.message}</div>`;
    }
  }
};

// Helper function
function escapeHtml(unsafe) {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

console.log('✅ ai.js loaded');
